Optional chroot building

diff --git a/git-pkg b/git-pkg
--- a/git-pkg
+++ b/git-pkg
@@ -10,7 +10,6 @@ USAGE='[-d=system|--dest=system] [-f|--force] [changelog|build]'
 
 . git-sh-setup
 . git-pkg-deb
-TYPES=deb
 
 
 ##### Common functions #####
@@ -29,14 +28,12 @@ check_version() {
     local head_commit=`git show --no-notes --format=format:%H HEAD | head -n 1`
 
     if [ "$last_tag_commit" != "$head_commit" -o -z "$last_tag" ]; then
-        if [ -n "$OPT_FORCE_REBUILD" ]; then
-            say "Forced building without new tag"
-        elif [ "$last_tag" == "$new_tag" ]; then
+        if [ "$last_tag" == "$new_tag" ]; then
             die "To build you must specify a new package version/release"
         else
             say "New build tag: $new_tag"
         fi
-    elif [ -z "$OPT_FORCE_REBUILD" ]; then
+    else
         die "Last build in tag \"$last_tag\", HEAD not updated"
     fi
 }
@@ -69,14 +66,14 @@ changelog() {
 build() {
     local version_tag=`echo "$PKG_TAG_FORMAT" \
         | sed -e "s/%t/$PKG_TYPE/g" \
-        | sed -e "s/%v/\`${PKG_TYPE}_last_version "$PKG_SCHROOT"\`/g" \
+        | sed -e "s/%v/\`${PKG_TYPE}_last_version\`/g" \
         | sed -e "s/%a/$PKG_ARCH/g" \
         | sed -e "s/%n/$PKG_DEST/g" \
         | sed -e "s/%m/$PKG_META/g"`
 
-    check_version "$version_tag"
-    ${PKG_TYPE}_build || die "Build error"
-    set_version "$version_tag"
+    [ -n "$OPT_FORCE_REBUILD" ] || check_version "$version_tag"
+    ${PKG_TYPE}_build || die "  --- Build error ---"
+    [ -n "$OPT_FORCE_REBUILD" ] || set_version "$version_tag"
 }
 
 
@@ -88,23 +85,33 @@ system_info() {
     say "  Type          $PKG_TYPE"
     say "  Arch          $PKG_ARCH"
     say "  Distr         $PKG_META"
-    schroot -c "$PKG_SCHROOT" -- /bin/true && say "  Schroot test  OK" || die "  Schroot test FAIL"
-    say
-    schroot -i "$PKG_SCHROOT"
+    if [ -n "$PKG_SCHROOT" ]; then
+        schroot -c "$PKG_SCHROOT" -- /bin/true && say "  Schroot test  OK" || die "  Schroot test FAIL"
+        say
+        schroot -i "$PKG_SCHROOT"
+    fi
     say
 }
 
 
 ##### Check configuration #####
 check_config() {
-    for var in schroot type arch; do
-        [ -n "`git config pkg."$PKG_DEST"."$var"`" ] || die "Git-pkg dest option pkg.$PKG_DEST.$var is not defined"
+    PKG_SCHROOT=`git config pkg."$PKG_DEST".schroot`
+    PKG_TYPE=`git config pkg."$PKG_DEST".type`
+    PKG_ARCH=`git config pkg."$PKG_DEST".arch || arch`
+    PKG_META=`git config pkg."$PKG_DEST".meta`
+    PKG_TAG_FORMAT=`git config pkg.tag-format || echo "pkg-%t-%n-%v-%a"`
+
+    EDITOR=`git config core.editor || echo "$EDITOR"`
+    FULLNAME=`git config user.name`
+    EMAIL=`git config user.email`
+
+    for var in PKG_TYPE PKG_ARCH EDITOR FULLNAME EMAIL; do
+        [ -n "`eval echo \\$"$var"`" ] || die "Variable \$$var is not defined"
     done
 
-    [ -n "$PKG_TAG_FORMAT" ] || die "Git-pkg option pkg.tag-format is not defined"
-    [ -n "$EDITOR" ] || die "\$EDITOR or core.editor is not defined"
     [ -n "`eval echo \\$PKG_TYPE_"$PKG_TYPE"`" ] || die "Unknown type \"$PKG_TYPE\" in pkg.$PKG_DEST.type"
-    [ -n "`schroot -l | grep "^chroot:$PKG_SCHROOT$"`" ] || die "Unknown chroot \"$PKG_SCHROOT\""
+    [ -z "$PKG_SCHROOT" -o -n "`schroot -l | grep "^chroot:$PKG_SCHROOT$"`" ] || die "Unknown chroot \"$PKG_SCHROOT\""
 
     ${PKG_TYPE}_check_config
 }
@@ -128,13 +135,6 @@ while test $# != "0"; do
 done
 [ -n "$PKG_DEST" ] || PKG_DEST=`git config pkg.default`
 [ -n "$PKG_DEST" ] || die "Please, specify a destination"
-
-PKG_SCHROOT=`git config pkg."$PKG_DEST".schroot`
-PKG_TYPE=`git config pkg."$PKG_DEST".type`
-PKG_ARCH=`git config pkg."$PKG_DEST".arch`
-PKG_META=`git config pkg."$PKG_DEST".meta`
-PKG_TAG_FORMAT=`git config pkg.tag-format || echo "pkg-%t-%n-%v-%a"`
-EDITOR=`git config core.editor || echo "$EDITOR"`
 
 case "$1" in
     c|changelog) check_config; changelog;;
